/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.AccountList;
import controllers.tokenList;
import java.util.ArrayList;
import javafx.scene.control.Alert;
import javax.swing.JOptionPane;
import models.Account;
import models.token;

/**
 *
 * @author Nadya Sirimanna
 */
public class CardPaymentUI extends javax.swing.JFrame {

    /**
     * Creates new form CardPaymentUI
     */
    
    public static float amount = 0;
    private static String user_tokenID;
    public CardPaymentUI(String tokenID) {
        initComponents();
        this.user_tokenID = tokenID;
        //cardp_lblcurrentBalance.setText(tokenID);
        
        EnterAmount.setVisible(true);
        InsertCard.setVisible(false);
        EnterPIN.setVisible(false);
    }

    public static String getUser_tokenID() {
        return user_tokenID;
    }

    public static void setUser_tokenID(String user_tokenID) {
        CardPaymentUI.user_tokenID = user_tokenID;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        EnterAmount = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cardp_amount = new javax.swing.JTextField();
        cardp_4 = new javax.swing.JButton();
        cardp_7 = new javax.swing.JButton();
        cardp_dot = new javax.swing.JButton();
        cardp_10 = new javax.swing.JButton();
        cardp_del = new javax.swing.JButton();
        cardp_9 = new javax.swing.JButton();
        cardp_8 = new javax.swing.JButton();
        cardp_5 = new javax.swing.JButton();
        cardp_2 = new javax.swing.JButton();
        cardp_3 = new javax.swing.JButton();
        cardp_6 = new javax.swing.JButton();
        cardp_btnEnterAmountBack = new javax.swing.JButton();
        cardp_btnProceed = new javax.swing.JButton();
        cardp_1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cardp_lblcurrentBalance = new javax.swing.JLabel();
        InsertCard = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cardp_btnInsertCardProceed = new javax.swing.JButton();
        cashp_btnInsertCardCancel = new javax.swing.JButton();
        EnterPIN = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cardp_btnEnterPINProceed = new javax.swing.JButton();
        cardp_btnEnterPINCancel = new javax.swing.JButton();
        cardp_p1 = new javax.swing.JButton();
        cardp_p2 = new javax.swing.JButton();
        cardp_p3 = new javax.swing.JButton();
        cardp_p0 = new javax.swing.JButton();
        cardp_p8 = new javax.swing.JButton();
        cardp_p5 = new javax.swing.JButton();
        cardp_p4 = new javax.swing.JButton();
        cardp_p7 = new javax.swing.JButton();
        cardp_p9 = new javax.swing.JButton();
        cardp_p6 = new javax.swing.JButton();
        cardp_pdel = new javax.swing.JButton();
        cardp_pin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Transit Authority");

        jLabel2.setText("Card Payment");

        jLabel3.setText("Enter Amount");

        cardp_4.setText("4");
        cardp_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardp_4ActionPerformed(evt);
            }
        });

        cardp_7.setText("7");
        cardp_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardp_7ActionPerformed(evt);
            }
        });

        cardp_dot.setText(".");
        cardp_dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardp_dotActionPerformed(evt);
            }
        });

        cardp_10.setText("0");
        cardp_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardp_10ActionPerformed(evt);
            }
        });

        cardp_del.setText("del");
        cardp_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardp_delActionPerformed(evt);
            }
        });

        cardp_9.setText("9");
        cardp_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardp_9ActionPerformed(evt);
            }
        });

        cardp_8.setText("8");
        cardp_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardp_8ActionPerformed(evt);
            }
        });

        cardp_5.setText("5");
        cardp_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardp_5ActionPerformed(evt);
            }
        });

        cardp_2.setText("2");
        cardp_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardp_2ActionPerformed(evt);
            }
        });

        cardp_3.setText("3");
        cardp_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardp_3ActionPerformed(evt);
            }
        });

        cardp_6.setText("6");
        cardp_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardp_6ActionPerformed(evt);
            }
        });

        cardp_btnEnterAmountBack.setText("Back");
        cardp_btnEnterAmountBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardp_btnEnterAmountBackActionPerformed(evt);
            }
        });

        cardp_btnProceed.setText("Proceed");
        cardp_btnProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardp_btnProceedActionPerformed(evt);
            }
        });

        cardp_1.setText("1");
        cardp_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardp_1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Your Current Balance is :");

        cardp_lblcurrentBalance.setText("Here");

        javax.swing.GroupLayout EnterAmountLayout = new javax.swing.GroupLayout(EnterAmount);
        EnterAmount.setLayout(EnterAmountLayout);
        EnterAmountLayout.setHorizontalGroup(
            EnterAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnterAmountLayout.createSequentialGroup()
                .addContainerGap(256, Short.MAX_VALUE)
                .addGroup(EnterAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardp_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EnterAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnterAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EnterAmountLayout.createSequentialGroup()
                                .addComponent(cardp_4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cardp_5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cardp_6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EnterAmountLayout.createSequentialGroup()
                                .addComponent(cardp_7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cardp_8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cardp_9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(EnterAmountLayout.createSequentialGroup()
                            .addComponent(cardp_dot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cardp_10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cardp_del, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(EnterAmountLayout.createSequentialGroup()
                        .addComponent(cardp_1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cardp_2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cardp_3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(205, 205, 205))
            .addGroup(EnterAmountLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel10)
                .addGap(29, 29, 29)
                .addComponent(cardp_lblcurrentBalance)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(EnterAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EnterAmountLayout.createSequentialGroup()
                    .addGroup(EnterAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(EnterAmountLayout.createSequentialGroup()
                            .addGap(247, 247, 247)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(EnterAmountLayout.createSequentialGroup()
                            .addGap(257, 257, 257)
                            .addGroup(EnterAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)))
                        .addGroup(EnterAmountLayout.createSequentialGroup()
                            .addGap(190, 190, 190)
                            .addGroup(EnterAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cardp_btnProceed)
                                .addGroup(EnterAmountLayout.createSequentialGroup()
                                    .addGap(132, 132, 132)
                                    .addComponent(cardp_btnEnterAmountBack)))))
                    .addContainerGap(223, Short.MAX_VALUE)))
        );
        EnterAmountLayout.setVerticalGroup(
            EnterAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnterAmountLayout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addGroup(EnterAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cardp_lblcurrentBalance))
                .addGap(51, 51, 51)
                .addComponent(cardp_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EnterAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardp_3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardp_2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardp_1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EnterAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardp_4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardp_5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardp_6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EnterAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardp_8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardp_7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardp_9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EnterAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardp_del, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardp_10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardp_dot, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
            .addGroup(EnterAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EnterAmountLayout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jLabel1)
                    .addGap(55, 55, 55)
                    .addComponent(jLabel2)
                    .addGap(33, 33, 33)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 313, Short.MAX_VALUE)
                    .addGroup(EnterAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cardp_btnProceed)
                        .addComponent(cardp_btnEnterAmountBack))
                    .addGap(37, 37, 37)))
        );

        jLabel4.setText("Transit Authority");

        jLabel5.setText("Card Payment");

        jLabel6.setText("PLEASE INSERT CARD");

        cardp_btnInsertCardProceed.setText("Proceed");
        cardp_btnInsertCardProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardp_btnInsertCardProceedActionPerformed(evt);
            }
        });

        cashp_btnInsertCardCancel.setText("Cancel");
        cashp_btnInsertCardCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashp_btnInsertCardCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InsertCardLayout = new javax.swing.GroupLayout(InsertCard);
        InsertCard.setLayout(InsertCardLayout);
        InsertCardLayout.setHorizontalGroup(
            InsertCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertCardLayout.createSequentialGroup()
                .addGroup(InsertCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InsertCardLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InsertCardLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(cardp_btnInsertCardProceed)
                        .addGap(96, 96, 96)
                        .addComponent(cashp_btnInsertCardCancel))
                    .addGroup(InsertCardLayout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel5))
                    .addGroup(InsertCardLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel6)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        InsertCardLayout.setVerticalGroup(
            InsertCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InsertCardLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(56, 56, 56)
                .addComponent(jLabel5)
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addGap(31, 31, 31)
                .addGroup(InsertCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardp_btnInsertCardProceed)
                    .addComponent(cashp_btnInsertCardCancel))
                .addGap(296, 296, 296))
        );

        jLabel7.setText("Transit Authority");

        jLabel8.setText("Card Payment");

        jLabel9.setText("Enter PIN");

        cardp_btnEnterPINProceed.setText("Proceed");
        cardp_btnEnterPINProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardp_btnEnterPINProceedActionPerformed(evt);
            }
        });

        cardp_btnEnterPINCancel.setText("Cancel");
        cardp_btnEnterPINCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardp_btnEnterPINCancelActionPerformed(evt);
            }
        });

        cardp_p1.setText("1");
        cardp_p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardp_p1ActionPerformed(evt);
            }
        });

        cardp_p2.setText("2");
        cardp_p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardp_p2ActionPerformed(evt);
            }
        });

        cardp_p3.setText("3");
        cardp_p3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardp_p3ActionPerformed(evt);
            }
        });

        cardp_p0.setText("0");
        cardp_p0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardp_p0ActionPerformed(evt);
            }
        });

        cardp_p8.setText("8");
        cardp_p8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardp_p8ActionPerformed(evt);
            }
        });

        cardp_p5.setText("5");
        cardp_p5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardp_p5ActionPerformed(evt);
            }
        });

        cardp_p4.setText("4");
        cardp_p4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardp_p4ActionPerformed(evt);
            }
        });

        cardp_p7.setText("7");
        cardp_p7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardp_p7ActionPerformed(evt);
            }
        });

        cardp_p9.setText("9");
        cardp_p9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardp_p9ActionPerformed(evt);
            }
        });

        cardp_p6.setText("6");
        cardp_p6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardp_p6ActionPerformed(evt);
            }
        });

        cardp_pdel.setText("del");
        cardp_pdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardp_pdelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EnterPINLayout = new javax.swing.GroupLayout(EnterPIN);
        EnterPIN.setLayout(EnterPINLayout);
        EnterPINLayout.setHorizontalGroup(
            EnterPINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnterPINLayout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnterPINLayout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addGroup(EnterPINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnterPINLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(248, 248, 248))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnterPINLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(235, 235, 235))))
            .addGroup(EnterPINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EnterPINLayout.createSequentialGroup()
                    .addGap(190, 190, 190)
                    .addGroup(EnterPINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(EnterPINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(EnterPINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnterPINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(EnterPINLayout.createSequentialGroup()
                                        .addComponent(cardp_p4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cardp_p5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cardp_p6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(EnterPINLayout.createSequentialGroup()
                                        .addComponent(cardp_p7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cardp_p8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cardp_p9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(EnterPINLayout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addComponent(cardp_p0, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cardp_pdel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(EnterPINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cardp_pin)
                                .addGroup(EnterPINLayout.createSequentialGroup()
                                    .addComponent(cardp_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cardp_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cardp_p3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(EnterPINLayout.createSequentialGroup()
                                .addComponent(cardp_btnEnterPINProceed)
                                .addGap(110, 110, 110)))
                        .addGroup(EnterPINLayout.createSequentialGroup()
                            .addGap(132, 132, 132)
                            .addComponent(cardp_btnEnterPINCancel)))
                    .addContainerGap(190, Short.MAX_VALUE)))
        );
        EnterPINLayout.setVerticalGroup(
            EnterPINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnterPINLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel7)
                .addGap(55, 55, 55)
                .addComponent(jLabel8)
                .addGap(32, 32, 32)
                .addComponent(jLabel9)
                .addContainerGap(367, Short.MAX_VALUE))
            .addGroup(EnterPINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EnterPINLayout.createSequentialGroup()
                    .addGap(185, 185, 185)
                    .addComponent(cardp_pin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(42, 42, 42)
                    .addGroup(EnterPINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cardp_p3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cardp_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cardp_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(EnterPINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cardp_p4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cardp_p5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cardp_p6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(EnterPINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cardp_p8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cardp_p7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cardp_p9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(EnterPINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cardp_pdel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cardp_p0, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                    .addGroup(EnterPINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cardp_btnEnterPINProceed)
                        .addComponent(cardp_btnEnterPINCancel))
                    .addGap(37, 37, 37)))
        );

        jLayeredPane1.setLayer(EnterAmount, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(InsertCard, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(EnterPIN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EnterAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(InsertCard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(EnterPIN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EnterAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(InsertCard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(EnterPIN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cardp_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardp_5ActionPerformed
        cardp_amount.setText(cardp_amount.getText() + "5");
    }//GEN-LAST:event_cardp_5ActionPerformed

    private void cardp_p5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardp_p5ActionPerformed
        cardp_pin.setText(cardp_pin.getText() + "5");
    }//GEN-LAST:event_cardp_p5ActionPerformed

    private void cardp_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardp_4ActionPerformed
        cardp_amount.setText(cardp_amount.getText() + "4");
    }//GEN-LAST:event_cardp_4ActionPerformed

    private void cardp_btnProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardp_btnProceedActionPerformed
        
        if("".equals(cardp_amount.getText())){
            JOptionPane.showMessageDialog(null,"Please enter an amout to proceed.","Warning",JOptionPane.WARNING_MESSAGE);
   
        } 
            else{
            amount = Float.parseFloat(cardp_amount.getText());
            InsertCard.setVisible(true);
            EnterAmount.setVisible(false);
            EnterPIN.setVisible(false);
            }
        
        
    }//GEN-LAST:event_cardp_btnProceedActionPerformed

    private void cardp_btnEnterAmountBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardp_btnEnterAmountBackActionPerformed
        
        PayStationUI paystation = new PayStationUI();
        paystation.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cardp_btnEnterAmountBackActionPerformed

    private void cardp_btnInsertCardProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardp_btnInsertCardProceedActionPerformed
        EnterPIN.setVisible(true);
        InsertCard.setVisible(false);
        EnterAmount.setVisible(false);
    }//GEN-LAST:event_cardp_btnInsertCardProceedActionPerformed

    private void cashp_btnInsertCardCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashp_btnInsertCardCancelActionPerformed
        // TODO add your handling code here:
        EnterPIN.setVisible(false);
        InsertCard.setVisible(false);
        EnterAmount.setVisible(true);
    }//GEN-LAST:event_cashp_btnInsertCardCancelActionPerformed

    private void cardp_btnEnterPINProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardp_btnEnterPINProceedActionPerformed
        if("".equals(cardp_pin.getText())){
            JOptionPane.showMessageDialog(null,"Please enter your PIN to proceed.","Warning",JOptionPane.WARNING_MESSAGE);
   
        } 
            else{
            AccountList actlist = new AccountList();
            tokenList token = new tokenList();
            ArrayList<Account> accArr = new ArrayList<Account>();
            ArrayList<token> foundToken = new ArrayList<token>();
            accArr = actlist.getAllAccounts();
            //Account account = new Account();
            foundToken = token.getTokenByID(user_tokenID);
            if(amount>0){
                actlist.updateBalance(amount, user_tokenID);
                JOptionPane.showMessageDialog(null,"You have successfully updated your account balance","Success",JOptionPane.INFORMATION_MESSAGE);
            }
            InsertCard.setVisible(true);
            EnterAmount.setVisible(false);
            EnterPIN.setVisible(false);
            }        
        
        
    }//GEN-LAST:event_cardp_btnEnterPINProceedActionPerformed

    private void cardp_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardp_1ActionPerformed
        cardp_amount.setText(cardp_amount.getText() + "1");
    }//GEN-LAST:event_cardp_1ActionPerformed

    private void cardp_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardp_2ActionPerformed
        cardp_amount.setText(cardp_amount.getText() + "2");
    }//GEN-LAST:event_cardp_2ActionPerformed

    private void cardp_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardp_3ActionPerformed
       cardp_amount.setText(cardp_amount.getText() + "3");
    }//GEN-LAST:event_cardp_3ActionPerformed

    private void cardp_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardp_6ActionPerformed
        cardp_amount.setText(cardp_amount.getText() + "6");
    }//GEN-LAST:event_cardp_6ActionPerformed

    private void cardp_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardp_7ActionPerformed
        cardp_amount.setText(cardp_amount.getText() + "7");
    }//GEN-LAST:event_cardp_7ActionPerformed

    private void cardp_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardp_8ActionPerformed
        cardp_amount.setText(cardp_amount.getText() + "8");
    }//GEN-LAST:event_cardp_8ActionPerformed

    private void cardp_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardp_9ActionPerformed
        cardp_amount.setText(cardp_amount.getText() + "9");
    }//GEN-LAST:event_cardp_9ActionPerformed

    private void cardp_dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardp_dotActionPerformed
        cardp_amount.setText(cardp_amount.getText() + ".");
    }//GEN-LAST:event_cardp_dotActionPerformed

    private void cardp_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardp_10ActionPerformed
        cardp_amount.setText(cardp_amount.getText() + "0");
    }//GEN-LAST:event_cardp_10ActionPerformed

    private void cardp_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardp_delActionPerformed
        
        int length = cardp_amount.getText().length();
        int amount = cardp_amount.getText().length() - 1;
        String store;
        if(length > 0){
            StringBuilder back = new StringBuilder(cardp_amount.getText());
            back.deleteCharAt(amount);
            store = back.toString();
            cardp_amount.setText(store);
            
        }
    }//GEN-LAST:event_cardp_delActionPerformed

    private void cardp_p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardp_p1ActionPerformed
        //i added
         cardp_pin.setText(cardp_pin.getText() + "1");
    }//GEN-LAST:event_cardp_p1ActionPerformed

    private void cardp_p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardp_p2ActionPerformed
        cardp_pin.setText(cardp_pin.getText() + "2");
    }//GEN-LAST:event_cardp_p2ActionPerformed

    private void cardp_p3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardp_p3ActionPerformed
        cardp_pin.setText(cardp_pin.getText() + "3");
    }//GEN-LAST:event_cardp_p3ActionPerformed

    private void cardp_p4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardp_p4ActionPerformed
        cardp_pin.setText(cardp_pin.getText() + "4");
    }//GEN-LAST:event_cardp_p4ActionPerformed

    private void cardp_p6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardp_p6ActionPerformed
        cardp_pin.setText(cardp_pin.getText() + "6");
    }//GEN-LAST:event_cardp_p6ActionPerformed

    private void cardp_p7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardp_p7ActionPerformed
        cardp_pin.setText(cardp_pin.getText() + "7");
    }//GEN-LAST:event_cardp_p7ActionPerformed

    private void cardp_p8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardp_p8ActionPerformed
        cardp_pin.setText(cardp_pin.getText() + "8");
    }//GEN-LAST:event_cardp_p8ActionPerformed

    private void cardp_p9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardp_p9ActionPerformed
        cardp_pin.setText(cardp_pin.getText() + "9");
    }//GEN-LAST:event_cardp_p9ActionPerformed

    private void cardp_p0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardp_p0ActionPerformed
        cardp_pin.setText(cardp_pin.getText() + "0");
    }//GEN-LAST:event_cardp_p0ActionPerformed

    private void cardp_pdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardp_pdelActionPerformed
       
        int length = cardp_pin.getText().length();
        int amountx = cardp_pin.getText().length() - 1;
        String store;
        if(length > 0){
            StringBuilder back = new StringBuilder(cardp_pin.getText());
            back.deleteCharAt(amountx);
            store = back.toString();
            cardp_pin.setText(store);
            
        }
        
        
        
    }//GEN-LAST:event_cardp_pdelActionPerformed

    private void cardp_btnEnterPINCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardp_btnEnterPINCancelActionPerformed
        // TODO add your handling code here:
        PayStationUI paystation = new PayStationUI();
        paystation.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cardp_btnEnterPINCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardPaymentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardPaymentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardPaymentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardPaymentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardPaymentUI(user_tokenID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EnterAmount;
    private javax.swing.JPanel EnterPIN;
    private javax.swing.JPanel InsertCard;
    private javax.swing.JButton cardp_1;
    private javax.swing.JButton cardp_10;
    private javax.swing.JButton cardp_2;
    private javax.swing.JButton cardp_3;
    private javax.swing.JButton cardp_4;
    private javax.swing.JButton cardp_5;
    private javax.swing.JButton cardp_6;
    private javax.swing.JButton cardp_7;
    private javax.swing.JButton cardp_8;
    private javax.swing.JButton cardp_9;
    private javax.swing.JTextField cardp_amount;
    private javax.swing.JButton cardp_btnEnterAmountBack;
    private javax.swing.JButton cardp_btnEnterPINCancel;
    private javax.swing.JButton cardp_btnEnterPINProceed;
    private javax.swing.JButton cardp_btnInsertCardProceed;
    private javax.swing.JButton cardp_btnProceed;
    private javax.swing.JButton cardp_del;
    private javax.swing.JButton cardp_dot;
    private javax.swing.JLabel cardp_lblcurrentBalance;
    private javax.swing.JButton cardp_p0;
    private javax.swing.JButton cardp_p1;
    private javax.swing.JButton cardp_p2;
    private javax.swing.JButton cardp_p3;
    private javax.swing.JButton cardp_p4;
    private javax.swing.JButton cardp_p5;
    private javax.swing.JButton cardp_p6;
    private javax.swing.JButton cardp_p7;
    private javax.swing.JButton cardp_p8;
    private javax.swing.JButton cardp_p9;
    private javax.swing.JButton cardp_pdel;
    private javax.swing.JTextField cardp_pin;
    private javax.swing.JButton cashp_btnInsertCardCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
