/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.AccountList;
import java.util.ArrayList;
import models.Account;

/**
 *
 * @author Nadya Sirimanna
 */
public class CashPaymentUI extends javax.swing.JFrame {

    /**
     * Creates new form CashPaymentUI
     */
    private static String user_tokenID;
    public CashPaymentUI(String tokenID) {
        this.user_tokenID = tokenID;
        initComponents();
    }

    public static String getUser_tokenID() {
        return user_tokenID;
    }

    public static void setUser_tokenID(String user_tokenID) {
        CashPaymentUI.user_tokenID = user_tokenID;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cashp_btnAmount = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cashp_1 = new javax.swing.JButton();
        cashp_2 = new javax.swing.JButton();
        cashp_3 = new javax.swing.JButton();
        cashp_4 = new javax.swing.JButton();
        cashp_5 = new javax.swing.JButton();
        cashp_6 = new javax.swing.JButton();
        cashp_7 = new javax.swing.JButton();
        cashp_8 = new javax.swing.JButton();
        cashp_9 = new javax.swing.JButton();
        cashp_btndel = new javax.swing.JButton();
        cashp_amount = new javax.swing.JTextField();
        cashp_10 = new javax.swing.JButton();
        cashp_btnProceed = new javax.swing.JButton();
        cashp_btnCancel = new javax.swing.JButton();
        cashp_lblSuccessMsg = new javax.swing.JLabel();
        cashp_dot = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("CASH PAYMENT");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(370, 140, 150, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Enter Amount   :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(290, 170, 120, 30);

        cashp_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cashp_1.setText("1");
        cashp_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashp_1ActionPerformed(evt);
            }
        });
        jPanel1.add(cashp_1);
        cashp_1.setBounds(330, 230, 49, 44);

        cashp_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cashp_2.setText("2");
        cashp_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashp_2ActionPerformed(evt);
            }
        });
        jPanel1.add(cashp_2);
        cashp_2.setBounds(390, 230, 49, 44);

        cashp_3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cashp_3.setText("3");
        cashp_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashp_3ActionPerformed(evt);
            }
        });
        jPanel1.add(cashp_3);
        cashp_3.setBounds(450, 230, 49, 44);

        cashp_4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cashp_4.setText("4");
        cashp_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashp_4ActionPerformed(evt);
            }
        });
        jPanel1.add(cashp_4);
        cashp_4.setBounds(330, 280, 49, 44);

        cashp_5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cashp_5.setText("5");
        cashp_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashp_5ActionPerformed(evt);
            }
        });
        jPanel1.add(cashp_5);
        cashp_5.setBounds(390, 280, 49, 44);

        cashp_6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cashp_6.setText("6");
        cashp_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashp_6ActionPerformed(evt);
            }
        });
        jPanel1.add(cashp_6);
        cashp_6.setBounds(450, 280, 49, 44);

        cashp_7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cashp_7.setText("7");
        cashp_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashp_7ActionPerformed(evt);
            }
        });
        jPanel1.add(cashp_7);
        cashp_7.setBounds(330, 330, 49, 44);

        cashp_8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cashp_8.setText("8");
        cashp_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashp_8ActionPerformed(evt);
            }
        });
        jPanel1.add(cashp_8);
        cashp_8.setBounds(390, 330, 49, 44);

        cashp_9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cashp_9.setText("9");
        cashp_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashp_9ActionPerformed(evt);
            }
        });
        jPanel1.add(cashp_9);
        cashp_9.setBounds(450, 330, 49, 44);

        cashp_btndel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cashp_btndel.setText("del");
        cashp_btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashp_btndelActionPerformed(evt);
            }
        });
        jPanel1.add(cashp_btndel);
        cashp_btndel.setBounds(450, 390, 49, 44);

        cashp_amount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(cashp_amount);
        cashp_amount.setBounds(410, 170, 159, 30);

        cashp_10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cashp_10.setText("0");
        cashp_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashp_10ActionPerformed(evt);
            }
        });
        jPanel1.add(cashp_10);
        cashp_10.setBounds(390, 390, 49, 44);

        cashp_btnProceed.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cashp_btnProceed.setText("Proceed");
        cashp_btnProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashp_btnProceedActionPerformed(evt);
            }
        });
        jPanel1.add(cashp_btnProceed);
        cashp_btnProceed.setBounds(330, 450, 83, 30);

        cashp_btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cashp_btnCancel.setText("Cancel");
        cashp_btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashp_btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(cashp_btnCancel);
        cashp_btnCancel.setBounds(430, 450, 73, 30);

        cashp_lblSuccessMsg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cashp_lblSuccessMsg.setText("Successful Message");
        jPanel1.add(cashp_lblSuccessMsg);
        cashp_lblSuccessMsg.setBounds(360, 210, 118, 17);

        cashp_dot.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cashp_dot.setText(".");
        cashp_dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashp_dotActionPerformed(evt);
            }
        });
        jPanel1.add(cashp_dot);
        cashp_dot.setBounds(330, 390, 49, 44);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extra/Logo_1.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(200, 0, 430, 130);

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extra/close.png"))); // NOI18N
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton2);
        jToggleButton2.setBounds(740, 20, 30, 30);

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extra/back.png"))); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1);
        jToggleButton1.setBounds(700, 20, 30, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extra/background.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(281, 281, 281))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cashp_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashp_5ActionPerformed
        cashp_amount.setText(cashp_amount.getText() + "5");
    }//GEN-LAST:event_cashp_5ActionPerformed

    private void cashp_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashp_1ActionPerformed
        cashp_amount.setText(cashp_amount.getText() + "1");
    }//GEN-LAST:event_cashp_1ActionPerformed

    private void cashp_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashp_2ActionPerformed
        cashp_amount.setText(cashp_amount.getText() + "2");
    }//GEN-LAST:event_cashp_2ActionPerformed

    private void cashp_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashp_3ActionPerformed
        cashp_amount.setText(cashp_amount.getText() + "3");
    }//GEN-LAST:event_cashp_3ActionPerformed

    private void cashp_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashp_4ActionPerformed
        cashp_amount.setText(cashp_amount.getText() + "4");
    }//GEN-LAST:event_cashp_4ActionPerformed

    private void cashp_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashp_6ActionPerformed
        cashp_amount.setText(cashp_amount.getText() + "6");
    }//GEN-LAST:event_cashp_6ActionPerformed

    private void cashp_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashp_7ActionPerformed
        cashp_amount.setText(cashp_amount.getText() + "7");
    }//GEN-LAST:event_cashp_7ActionPerformed

    private void cashp_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashp_8ActionPerformed
        cashp_amount.setText(cashp_amount.getText() + "8");
    }//GEN-LAST:event_cashp_8ActionPerformed

    private void cashp_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashp_9ActionPerformed
        cashp_amount.setText(cashp_amount.getText() + "9");
    }//GEN-LAST:event_cashp_9ActionPerformed

    private void cashp_dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashp_dotActionPerformed
        cashp_amount.setText(cashp_amount.getText() + ".");
    }//GEN-LAST:event_cashp_dotActionPerformed

    private void cashp_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashp_10ActionPerformed
        cashp_amount.setText(cashp_amount.getText() + "0");
    }//GEN-LAST:event_cashp_10ActionPerformed

    private void cashp_btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashp_btndelActionPerformed
        
        int length = cashp_amount.getText().length();
        int amount = cashp_amount.getText().length() - 1;
        String store;
        if(length > 0){
            StringBuilder back = new StringBuilder(cashp_amount.getText());
            back.deleteCharAt(amount);
            store = back.toString();
            cashp_amount.setText(store);
            
        }
    }//GEN-LAST:event_cashp_btndelActionPerformed

    private void cashp_btnProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashp_btnProceedActionPerformed
        Double amount = Double.parseDouble(cashp_amount.getText());
        //get these into a method in the payment method
        AccountList actlist = new AccountList();
        ArrayList<Account> accArr = new ArrayList<Account>();
        accArr = actlist.getAllAccounts();
        
        
    }//GEN-LAST:event_cashp_btnProceedActionPerformed

    private void cashp_btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashp_btnCancelActionPerformed
        
        PayStationUI psui = new PayStationUI();
        psui.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_cashp_btnCancelActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        new PayStationUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashPaymentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashPaymentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashPaymentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashPaymentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashPaymentUI(user_tokenID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cardp_btnEnterAmountBack;
    private javax.swing.JButton cardp_btnEnterAmountBack1;
    private javax.swing.JButton cashp_1;
    private javax.swing.JButton cashp_10;
    private javax.swing.JButton cashp_2;
    private javax.swing.JButton cashp_3;
    private javax.swing.JButton cashp_4;
    private javax.swing.JButton cashp_5;
    private javax.swing.JButton cashp_6;
    private javax.swing.JButton cashp_7;
    private javax.swing.JButton cashp_8;
    private javax.swing.JButton cashp_9;
    private javax.swing.JTextField cashp_amount;
    private javax.swing.ButtonGroup cashp_btnAmount;
    private javax.swing.JButton cashp_btnCancel;
    private javax.swing.JButton cashp_btnProceed;
    private javax.swing.JButton cashp_btndel;
    private javax.swing.JButton cashp_dot;
    private javax.swing.JLabel cashp_lblSuccessMsg;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
