/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.AccountList;
import java.util.ArrayList;
import models.Account;

/**
 *
 * @author Nadya Sirimanna
 */
public class CashPaymentUI extends javax.swing.JFrame {

    /**
     * Creates new form CashPaymentUI
     */
    private static String user_tokenID;
    public CashPaymentUI(String tokenID) {
        this.user_tokenID = tokenID;
        initComponents();
    }

    public static String getUser_tokenID() {
        return user_tokenID;
    }

    public static void setUser_tokenID(String user_tokenID) {
        CashPaymentUI.user_tokenID = user_tokenID;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cashp_btnAmount = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cashp_1 = new javax.swing.JButton();
        cashp_2 = new javax.swing.JButton();
        cashp_3 = new javax.swing.JButton();
        cashp_4 = new javax.swing.JButton();
        cashp_5 = new javax.swing.JButton();
        cashp_6 = new javax.swing.JButton();
        cashp_7 = new javax.swing.JButton();
        cashp_8 = new javax.swing.JButton();
        cashp_9 = new javax.swing.JButton();
        cashp_btndel = new javax.swing.JButton();
        cashp_amount = new javax.swing.JTextField();
        cashp_10 = new javax.swing.JButton();
        cashp_btnProceed = new javax.swing.JButton();
        cashp_btnCancel = new javax.swing.JButton();
        cashp_lblSuccessMsg = new javax.swing.JLabel();
        cashp_dot = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Transit Authority");

        jLabel2.setText("Cash Payment");

        jLabel3.setText("Enter Amount");

        cashp_1.setText("1");
        cashp_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashp_1ActionPerformed(evt);
            }
        });

        cashp_2.setText("2");
        cashp_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashp_2ActionPerformed(evt);
            }
        });

        cashp_3.setText("3");
        cashp_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashp_3ActionPerformed(evt);
            }
        });

        cashp_4.setText("4");
        cashp_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashp_4ActionPerformed(evt);
            }
        });

        cashp_5.setText("5");
        cashp_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashp_5ActionPerformed(evt);
            }
        });

        cashp_6.setText("6");
        cashp_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashp_6ActionPerformed(evt);
            }
        });

        cashp_7.setText("7");
        cashp_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashp_7ActionPerformed(evt);
            }
        });

        cashp_8.setText("8");
        cashp_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashp_8ActionPerformed(evt);
            }
        });

        cashp_9.setText("9");
        cashp_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashp_9ActionPerformed(evt);
            }
        });

        cashp_btndel.setText("del");
        cashp_btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashp_btndelActionPerformed(evt);
            }
        });

        cashp_10.setText("0");
        cashp_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashp_10ActionPerformed(evt);
            }
        });

        cashp_btnProceed.setText("Proceed");
        cashp_btnProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashp_btnProceedActionPerformed(evt);
            }
        });

        cashp_btnCancel.setText("Cancel");
        cashp_btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashp_btnCancelActionPerformed(evt);
            }
        });

        cashp_lblSuccessMsg.setText("Successful Message");

        cashp_dot.setText(".");
        cashp_dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashp_dotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cashp_4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cashp_5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cashp_6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cashp_7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cashp_8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cashp_9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cashp_dot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cashp_10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cashp_btndel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cashp_amount)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cashp_1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cashp_2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cashp_3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cashp_btnProceed)
                                .addGap(18, 18, 18)
                                .addComponent(cashp_btnCancel)))
                        .addGap(167, 167, 167))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cashp_lblSuccessMsg)
                        .addGap(210, 210, 210))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(209, 209, 209))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(78, 78, 78)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(cashp_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cashp_lblSuccessMsg)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashp_3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashp_2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashp_1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashp_4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashp_5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashp_6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashp_8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashp_7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashp_9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashp_btndel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashp_10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashp_dot, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashp_btnProceed)
                    .addComponent(cashp_btnCancel))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cashp_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashp_5ActionPerformed
        cashp_amount.setText(cashp_amount.getText() + "5");
    }//GEN-LAST:event_cashp_5ActionPerformed

    private void cashp_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashp_1ActionPerformed
        cashp_amount.setText(cashp_amount.getText() + "1");
    }//GEN-LAST:event_cashp_1ActionPerformed

    private void cashp_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashp_2ActionPerformed
        cashp_amount.setText(cashp_amount.getText() + "2");
    }//GEN-LAST:event_cashp_2ActionPerformed

    private void cashp_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashp_3ActionPerformed
        cashp_amount.setText(cashp_amount.getText() + "3");
    }//GEN-LAST:event_cashp_3ActionPerformed

    private void cashp_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashp_4ActionPerformed
        cashp_amount.setText(cashp_amount.getText() + "4");
    }//GEN-LAST:event_cashp_4ActionPerformed

    private void cashp_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashp_6ActionPerformed
        cashp_amount.setText(cashp_amount.getText() + "6");
    }//GEN-LAST:event_cashp_6ActionPerformed

    private void cashp_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashp_7ActionPerformed
        cashp_amount.setText(cashp_amount.getText() + "7");
    }//GEN-LAST:event_cashp_7ActionPerformed

    private void cashp_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashp_8ActionPerformed
        cashp_amount.setText(cashp_amount.getText() + "8");
    }//GEN-LAST:event_cashp_8ActionPerformed

    private void cashp_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashp_9ActionPerformed
        cashp_amount.setText(cashp_amount.getText() + "9");
    }//GEN-LAST:event_cashp_9ActionPerformed

    private void cashp_dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashp_dotActionPerformed
        cashp_amount.setText(cashp_amount.getText() + ".");
    }//GEN-LAST:event_cashp_dotActionPerformed

    private void cashp_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashp_10ActionPerformed
        cashp_amount.setText(cashp_amount.getText() + "0");
    }//GEN-LAST:event_cashp_10ActionPerformed

    private void cashp_btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashp_btndelActionPerformed
        
        int length = cashp_amount.getText().length();
        int amount = cashp_amount.getText().length() - 1;
        String store;
        if(length > 0){
            StringBuilder back = new StringBuilder(cashp_amount.getText());
            back.deleteCharAt(amount);
            store = back.toString();
            cashp_amount.setText(store);
            
        }
    }//GEN-LAST:event_cashp_btndelActionPerformed

    private void cashp_btnProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashp_btnProceedActionPerformed
        Double amount = Double.parseDouble(cashp_amount.getText());
        //get these into a method in the payment method
        AccountList actlist = new AccountList();
        ArrayList<Account> accArr = new ArrayList<Account>();
        accArr = actlist.getAllAccounts();
        
        
    }//GEN-LAST:event_cashp_btnProceedActionPerformed

    private void cashp_btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashp_btnCancelActionPerformed
        
        PayStationUI psui = new PayStationUI();
        psui.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_cashp_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashPaymentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashPaymentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashPaymentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashPaymentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashPaymentUI(user_tokenID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cashp_1;
    private javax.swing.JButton cashp_10;
    private javax.swing.JButton cashp_2;
    private javax.swing.JButton cashp_3;
    private javax.swing.JButton cashp_4;
    private javax.swing.JButton cashp_5;
    private javax.swing.JButton cashp_6;
    private javax.swing.JButton cashp_7;
    private javax.swing.JButton cashp_8;
    private javax.swing.JButton cashp_9;
    private javax.swing.JTextField cashp_amount;
    private javax.swing.ButtonGroup cashp_btnAmount;
    private javax.swing.JButton cashp_btnCancel;
    private javax.swing.JButton cashp_btnProceed;
    private javax.swing.JButton cashp_btndel;
    private javax.swing.JButton cashp_dot;
    private javax.swing.JLabel cashp_lblSuccessMsg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
