/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.AccountList;
import controllers.tokenList;
import controllers.tokenReader;
import java.util.ArrayList;
import models.Account;
import models.token;

/**
 *
 * @author Nadya Sirimanna
 */
public class PayStationUI extends javax.swing.JFrame {

    /**
     * Creates new form ScanTicket
     */
    private static String user_tokenID;
    public PayStationUI() {
        initComponents();
        main.setVisible(true);
        NewAccount.setVisible(false);
        readToken.setVisible(false);
        readBalance.setVisible(false);
        
    }

    public String getUser_tokenID() {
        return user_tokenID;
    }

    public void setUser_tokenID(String user_tokenID) {
        this.user_tokenID = user_tokenID;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        readToken = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ps_tokenID = new javax.swing.JTextField();
        ps_btnScanToken = new javax.swing.JButton();
        readBalance = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ps_currentBalance = new javax.swing.JTextField();
        ps_btnPayWithCash = new javax.swing.JButton();
        ps_btnPayWithCard = new javax.swing.JButton();
        ps_btnExitAccount = new javax.swing.JButton();
        main = new javax.swing.JPanel();
        ps_btnMainNewUser = new javax.swing.JButton();
        ps_mainAddPayment = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        NewAccount = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ps_na_UserID = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ps_na_username = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ps_na_TokenID = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ps_na_amount = new javax.swing.JTextField();
        ps_na_btnproceed = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Transit Authority");

        readToken.setPreferredSize(new java.awt.Dimension(527, 406));

        jLabel2.setText("Scan Your Token Here");

        ps_btnScanToken.setText("Proceed");
        ps_btnScanToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps_btnScanTokenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout readTokenLayout = new javax.swing.GroupLayout(readToken);
        readToken.setLayout(readTokenLayout);
        readTokenLayout.setHorizontalGroup(
            readTokenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(readTokenLayout.createSequentialGroup()
                .addGroup(readTokenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(readTokenLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel2))
                    .addGroup(readTokenLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(ps_tokenID, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(readTokenLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(ps_btnScanToken)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        readTokenLayout.setVerticalGroup(
            readTokenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(readTokenLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel2)
                .addGap(49, 49, 49)
                .addComponent(ps_tokenID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(ps_btnScanToken)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        readBalance.setPreferredSize(new java.awt.Dimension(527, 358));

        jLabel3.setText("Current Balance");

        ps_btnPayWithCash.setText("Pay With Cash");
        ps_btnPayWithCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps_btnPayWithCashActionPerformed(evt);
            }
        });

        ps_btnPayWithCard.setText("Pay With Card");
        ps_btnPayWithCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps_btnPayWithCardActionPerformed(evt);
            }
        });

        ps_btnExitAccount.setText("Exit Account");
        ps_btnExitAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps_btnExitAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout readBalanceLayout = new javax.swing.GroupLayout(readBalance);
        readBalance.setLayout(readBalanceLayout);
        readBalanceLayout.setHorizontalGroup(
            readBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, readBalanceLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(ps_btnPayWithCash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(ps_btnPayWithCard)
                .addGap(74, 74, 74)
                .addComponent(ps_btnExitAccount)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, readBalanceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(readBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, readBalanceLayout.createSequentialGroup()
                        .addComponent(ps_currentBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, readBalanceLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(224, 224, 224))))
        );
        readBalanceLayout.setVerticalGroup(
            readBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(readBalanceLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(49, 49, 49)
                .addComponent(ps_currentBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(readBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ps_btnPayWithCard)
                    .addComponent(ps_btnPayWithCash)
                    .addComponent(ps_btnExitAccount))
                .addGap(117, 117, 117))
        );

        main.setMinimumSize(new java.awt.Dimension(527, 406));

        ps_btnMainNewUser.setText("Register as a New User");
        ps_btnMainNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps_btnMainNewUserActionPerformed(evt);
            }
        });

        ps_mainAddPayment.setText("Top Up Account");
        ps_mainAddPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps_mainAddPaymentActionPerformed(evt);
            }
        });

        jLabel4.setText("Transit Authority");

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(ps_btnMainNewUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(ps_mainAddPayment)
                .addGap(130, 130, 130))
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ps_btnMainNewUser)
                    .addComponent(ps_mainAddPayment))
                .addGap(85, 85, 85))
        );

        NewAccount.setMinimumSize(new java.awt.Dimension(527, 406));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("User Details"));

        jLabel5.setText("User ID");

        ps_na_UserID.setText("User ID");

        jLabel7.setText("User Name");

        ps_na_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps_na_usernameActionPerformed(evt);
            }
        });

        jLabel8.setText("Token ID");

        ps_na_TokenID.setText("Token ID");

        jLabel10.setText("amount");

        ps_na_btnproceed.setText("Proceed");
        ps_na_btnproceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps_na_btnproceedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ps_na_TokenID)
                    .addComponent(ps_na_UserID)
                    .addComponent(ps_na_username, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(ps_na_amount))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(285, Short.MAX_VALUE)
                .addComponent(ps_na_btnproceed)
                .addGap(159, 159, 159))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ps_na_UserID))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ps_na_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ps_na_TokenID))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ps_na_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addComponent(ps_na_btnproceed)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout NewAccountLayout = new javax.swing.GroupLayout(NewAccount);
        NewAccount.setLayout(NewAccountLayout);
        NewAccountLayout.setHorizontalGroup(
            NewAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        NewAccountLayout.setVerticalGroup(
            NewAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(readToken, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(readBalance, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(main, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(NewAccount, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(readToken, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(221, 221, 221))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(readBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(213, 213, 213)
                    .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(214, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(213, 213, 213)
                    .addComponent(NewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(214, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 334, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(readToken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 52, Short.MAX_VALUE)
                    .addComponent(readBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(153, 153, 153)
                    .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(153, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(153, 153, 153)
                    .addComponent(NewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(153, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ps_btnExitAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps_btnExitAccountActionPerformed
        login loginUI = new login();
        loginUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ps_btnExitAccountActionPerformed

    private void ps_btnScanTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps_btnScanTokenActionPerformed
        
        String tokenID = ps_tokenID.getText();
        tokenList tokens = new tokenList();
        //tokenList tokenlist = new tokenList();
        tokenReader tknRead = new tokenReader();
        ArrayList<token> token = new ArrayList<token>();
        token token1 = new token();
        String infomsg;
        String Titlebar;
        
        if ( tokens.findTokenByID(tokenID) ){
            user_tokenID = tokenID;
            infomsg = "Valid token ID";
            Titlebar = "Success";
            tknRead.displayConfirmationMessage(infomsg, Titlebar);
            String accBalance = Double.toString(tokens.getBalannce(tokenID));
            ps_currentBalance.setText(accBalance);
            
            readToken.setVisible(false);
            readBalance.setVisible(true);
        }
        else {
            infomsg = "Invalid token ID";
            Titlebar = "Unsuccessful";
            tknRead.displayConfirmationMessage(infomsg, Titlebar);
        }
    }//GEN-LAST:event_ps_btnScanTokenActionPerformed

    private void ps_btnPayWithCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps_btnPayWithCashActionPerformed
        // TODO add your handling code here:
        CashPaymentUI cashpayment = new CashPaymentUI(user_tokenID);
        cashpayment.setUser_tokenID(user_tokenID);
        cashpayment.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ps_btnPayWithCashActionPerformed

    private void ps_btnPayWithCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps_btnPayWithCardActionPerformed
        // TODO add your handling code here:
        CardPaymentUI cardpayment = new CardPaymentUI(user_tokenID);
        cardpayment.setUser_tokenID(user_tokenID);
        cardpayment.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ps_btnPayWithCardActionPerformed

    private void ps_btnMainNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps_btnMainNewUserActionPerformed
        // TODO add your handling code here:
        
        main.setVisible(false);
        NewAccount.setVisible(true);
        readToken.setVisible(false);
        readBalance.setVisible(false);
        
    }//GEN-LAST:event_ps_btnMainNewUserActionPerformed

    private void ps_mainAddPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps_mainAddPaymentActionPerformed
        // TODO add your handling code here:
        main.setVisible(false);
        NewAccount.setVisible(false);
        readToken.setVisible(true);
        readBalance.setVisible(false);
    }//GEN-LAST:event_ps_mainAddPaymentActionPerformed

    private void ps_na_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps_na_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ps_na_usernameActionPerformed

    private void ps_na_btnproceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps_na_btnproceedActionPerformed
        // TODO add your handling code here:
        token token1 = new token();
        int usercount = Account.getAccountCount() + 1;
        ps_na_UserID.setText(Integer.toString(usercount));
        String userName = ps_na_username.getText();
        int tokencount = token1.getCount();
        ps_na_TokenID.setText(Integer.toString(tokencount));
        Double amount = Double.parseDouble(ps_na_amount.getText());
        
        Account account = new Account(token1,userName,amount);
        
        AccountList accountlist = new AccountList();
        tokenList tokenlist = new tokenList();
        tokenlist.add(token1);
        accountlist.addAccount(account);
    }//GEN-LAST:event_ps_na_btnproceedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayStationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayStationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayStationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayStationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayStationUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NewAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel main;
    private javax.swing.JButton ps_btnExitAccount;
    private javax.swing.JButton ps_btnMainNewUser;
    private javax.swing.JButton ps_btnPayWithCard;
    private javax.swing.JButton ps_btnPayWithCash;
    private javax.swing.JButton ps_btnScanToken;
    private javax.swing.JTextField ps_currentBalance;
    private javax.swing.JButton ps_mainAddPayment;
    private javax.swing.JLabel ps_na_TokenID;
    private javax.swing.JLabel ps_na_UserID;
    private javax.swing.JTextField ps_na_amount;
    private javax.swing.JButton ps_na_btnproceed;
    private javax.swing.JTextField ps_na_username;
    private javax.swing.JTextField ps_tokenID;
    private javax.swing.JPanel readBalance;
    private javax.swing.JPanel readToken;
    // End of variables declaration//GEN-END:variables
}
